version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}  
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASS}
      ME_CONFIG_BASICAUTH: true  

  graphql:
    image: graphql:latest
    restart: always
    ports:
      - 4000:4000
    build:
      context: graphql
      dockerfile: Dockerfile
    environment:
      DB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}/${DB_NAME}?authSource=admin
      NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - mongo
      - mongo-express

  processor:
    image: indexer:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}/${DB_NAME}?authSource=admin
      NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - mongo
      - mongo-express
